### ISSUE TITLE
Your signup email is wasting my time

### ISSUE THREAD

**Issue by comready** [Automattic/Simplenote-United#113]
It should say something like - "Please click this link to verfiy your email address. If you did not sign up please ignore this email."

Obviously someone else used my email address to sign up but the email I received had no "click to verify" and no "please ignore this email. That wastes my time as I have to think whether my email password has been hacked or not.

**Comment by comready** [comment]
It seems someone else reported this problem back in 2019 

https://twitter.com/simplenoteapp/status/1147558481895071745?lang=en

Why was it not fixed?

**Comment by jleandroperez** [comment]
We're in the process of rolling out email verification.  I'll pass the feedback along, **thank you**!

P.s.: Please feel free to contact us at `support@simplenote.com` for support requests, if needed.
