### ISSUE TITLE
Crypto Address Titled Notes Causing Sync issues

### ISSUE THREAD

**Issue by azollafox** [Automattic/Simplenote-United#136]
### Expected
No matter what text I put in the title of my notes, they should be accessible and sync.

### Observed
The user created a note with no title, the title itself was a crypto address. This note caused a lack of sync (and also kept coming back despite multiple attempts at deleting it). The content was a BTC crypto address.\

### Reproduced

I don't have a crypto address handy, so I couldn't reproduce this

### Where did you see the bug
zen-5183352

**Comment by dmsnell** [comment]
After reviewing the ticket it sounds like this is more likely an issue in one of the Simperium libraries where it sometimes loses track of the sync for deleted entities. It does not seem like this could be related to the note title.

To that end it's probably better rolled into existing issues with those libraries, though I don't know off-hand which ones. It is not a unique issue though.

**Comment by codebykat** [comment]
Closing as not really actionable without more info.
