### ISSUE TITLE
Login with wordpress doesn't work

### ISSUE THREAD

**Issue by songsammy** [Automattic/Simplenote-United#143]
I tried to login via simplenote-android,simplenote-electron,app.simplenote.com, not being able to login.
### Expected
Login to my account as usual.

### Observed
On android app and simplenote-electron, after clicking the "authorize" button, it did worked for a split second and then it logged out by itself and wanted me to log in.   
On web page, after authorizing via wordpress, it did return to app.simplenote.com, but the page is blank.
#### webpage
1. open app.simplenote.com
2. Click "Login with wordpress"
3. _being redirected to public-api.wordpress.com_
4. Click authorize (I have logged in my wordpress before)
5. _being redirected to app.simplenote.com_
6. _The main page containing all notes appeared, but all my notes were gone _
7. _I did nothing, and was redirected to log in again_
I tried to login via simplenote-android,simplenote-electron,app.simplenote.com, not being able to login.
### Expected
Login to my account as usual.

### Observed
On android app and simplenote-electron, after clicking the "authorize" button, it did worked for a split second and then it logged out by itself and wanted me to log in.   
On web page, after authorizing via wordpress, it did return to app.simplenote.com, but the page is blank.
#### webpage
1. open app.simplenote.com
2. Click "Login with wordpress"
3. _being redirected to public-api.wordpress.com_
4. Click authorize (I have logged in my wordpress before)
5. _being redirected to app.simplenote.com_
6. _The main page containing all notes appeared, but all my notes were gone _
7. _I did nothing, and was redirected to log in again_

### Where did you see the bug

- System Make: 
- System Model:
- OS: Ubuntu
- OS version:20.04.1
- Browser (if applicable): Firefox
- Browser version (if applicable):104.0
- Simplenote app version:

### Where did you see the bug

- System Make: 
- System Model:
- OS: Ubuntu
- OS version:20.04.1
- Browser (if applicable): Firefox
- Browser version (if applicable):104.0
- Simplenote app version:

**Comment by codebykat** [comment]
Hi @songsammy, thanks for this report. We had an issue on the server-side which has since been fixed. If you're still having trouble logging in, please drop us a line at support@simplenote.com so we can look at your account specifically. Thanks!
