### ISSUE TITLE
"ReferenceError: _gaq is not defined" on published notes

### ISSUE THREAD

**Issue by Krinkle** [Automattic/Simplenote-United#144]
### Expected
No JS erorrs.

### Observed

```
Uncaught ReferenceError: _gaq is not defined
at onclick
```

### Reproduced

1. https://app.simplenote.com/publish/XQQQCS
2. Cmd-click link to open in new tab, or, click normally and make sure console is already open with "Preserve logs" ticked in the DevTools settings.

I guess this is a left-over from a time where third-party Google Analytics were integrated client-side by Simplenote. This is fortunately no longer the case on published notes, but there is still an old GA onclick attribute in the footer.

### Where did you see the bug
- Browser: Firefox, Safari, Chrome.

**Comment by codebykat** [comment]
Huh, interesting find. I'm not actually seeing that in the logs but I do see a few stray calls in the code. Will try to clean it up at some point.

Edited: Oh, I see, I think it only throws an error when you click on the link in the footer.

**Comment by codebykat** [comment]
Fixed, thanks for the report!
