### ISSUE TITLE
Add Sync Status Indicator

### ISSUE THREAD

**Issue by roundhill** [Automattic/Simplenote-United#17]
Let's display to the user the sync status for a note, to avoid things like:

> We really need to figure out messaging sync on launch. The only time I "lose" things now is when I open app, edit a note thinking it's caught up, and it overwrites a newer version from another client. Especially on a slower connection — we need to stop pretending sync and status doesn't exist

**Comment by tbradsha** [comment]
Requested for Android: #2189448-zen

**Comment by thehenrybyrd** [comment]
Another request in #2298711-zen

> using Simplenote on windows, I miss the little "saving/saved" message that used to pop up at the top right of screen.

I also noticed two requests for this in the electron repo:
https://github.com/Automattic/simplenote-electron/issues/1243
https://github.com/Automattic/simplenote-electron/issues/1537

**Comment by rachelmcr** [comment]
This came up again in feedback from a beta tester on Android (using 2.5-rc-1):

> great app, sometimes you need to close the app and open to re sync. Would be useful to add a sync status button so at least its easy to know if its synced to the cloud or not

**Comment by rachelmcr** [comment]
I noticed we're also tracking this idea internally (internal ref: p7rJFO-t-p2). @belcherj  should we keep this issue open or should this only be tracked internally with other feature requests?

**Comment by belcherj** [comment]
Let's close here as this is a feature request.  TY.
