### ISSUE TITLE
Within-Note Search

### ISSUE THREAD

**Issue by roundhill** [Automattic/Simplenote-United#19]
Search within a note needs to be fully integrated and really nice, showing how many times a string occurs, where it is location wise, making it easy to go in between instances within a note. When search returns no hits we should offer to start a note. Clicking on search should show the last 5 searches as saved "search history" and this should be synced.

**Comment by codebykat** [comment]
This is mostly done or in-progress across all apps! Closing this issue since it is tracked elsewhere.
