### ISSUE TITLE
Inter-Note Linking

### ISSUE THREAD

**Issue by roundhill** [Automattic/Simplenote-United#20]
Inter-note linking. This is a potentially huge one because it's introducing rich text into our main text screen, but basically this is a way to have ID-based links between notes in your notebook, but maybe we can leverage some of the work Hogwarts is doing for WP apps.

**Comment by jamesacampbell** [comment]
Is this going to happen? Would love this feature.

**Comment by codebykat** [comment]
https://simplenote.com/2020/11/03/introducing-internal-links/ 😄
