### ISSUE TITLE
Previewing notes default to LTR on notes with bidirectional content

### ISSUE THREAD

**Issue by liviopv** [Automattic/Simplenote-United#26]
When you have a markdown note that that includes content from RLT languages and LTR languages, the Preview will default to LTR

### Expected
The RTL part should be displayed with RTL alignment on Preview

### Observed
The RTL part was displayed with LTR alignment

### Reproduced
> 1. Open a new markdown formatted note
> 2. Add some LTR content
> 3. Add some RTL content
> 4. Preview the note

![Screenshot](https://cld.wthms.co/Dx0gxU+)
Screenshot: https://cld.wthms.co/Dx0gxU

***(Required)*** Replace SYSTEM_MAKE, SYSTEM_MODEL, OS_VERSION, and APP_VERSION below with the details for the system running the Simplenote app.  If you reproduced the bug on multiple systems, please add a row for each system.

Make|Model|OS Version|App Version
Affects all apps, in all OS.

Tested on old web app and Mac Electron. Latest versions of the app and Mac OS.

User-report: 2037089-zen

**Comment by rachelmcr** [comment]
This looks like the same issue reported in https://github.com/Automattic/Simplenote-United/issues/28.
