### ISSUE TITLE
Korean Characters not Printing Correctly Consistently

### ISSUE THREAD

**Issue by ChrissiePollock** [Automattic/Simplenote-United#33]
- Fedora 27 cinnamon > Simplenote binaries
 - Android mobile app

> In korean, there are many characters, which could be combined by other characters on typing, realtime.
> 
> Like in English, W.W is actually atomic and complete character. But only with appearance, you could divide that character to 2 'v's.
> When I am typing Korean, there was a case like this. When I want to type 않, I should press ㅇ for the first, and ㅏ for the second, which makes 아. If I press ㄴ on 아, that makes 안. Finally I add ㅎ, my cute macbook air returns 않.
> 
> So, transformating progress is like this. ㅇ > 아 > 안 > 않.
> 
> Simplenote input stream seems to break the rule above because of maybe race condition of input stream. Because when I type slowly, it works pretty well.
> 
> When I type 않 6 times, I get result like this.
> 않ㅇ낳낳ㅇ낳ㅇ낳낳
> ㅇ낳 is result of typings of ㅇ>ㄴ>ㅏ>ㅎ, While my typing was ㅇ>ㅏ>ㄴ>ㅎ.
> 
> And I think there is case ignoring user's input. Cuz there was 낳, which cut off ㅇ from input and mixed the sequence.

#1062993-zen

**Comment by rezzap** [comment]
There is another user report of what looks very similar to this for Japanese symbols in 2553036-zen

> I can't append Chinese character after finished the last input session. However, the characters seems successfully saved.

They've provided this gif

![Japanase Character Duplicating](https://user-images.githubusercontent.com/10325627/70986974-e832c700-20b6-11ea-9b00-d8892202ed14.gif)

Simplenote MAC OS:1.8
MacOS:10.13.6 (17G9016)
InputMethod:搜狗输入法 5.6.0.10272

They advised this does not replicate in the web application.

**Comment by thehenrybyrd** [comment]
Possible report in #2626282-zen. Could also be https://github.com/Automattic/simplenote-electron/issues/1511, so waiting for more details (and hopefully screencast).

**Comment by SiobhyB** [comment]
There's another possible report of this in 2777608-zen. The user noticed that Arabic characters are unreadable since updating to the latest version of the iOS app (4.15.1). This issue is specific to the notes list, the individual notes are readable. The web app also works as expected for them.

I've asked for some more details, as I wasn't able to notice any differences between the web and iOS apps after creating a couple of notes using Arabic characters in my testing.

**Comment by rezzap** [comment]
There is another report of this but for tags in 3560420-zd-woothemes. 

Model : apple / iphone 11 pro
IOS or version : IOS 14.2
Type of the Simplenote app and its version : version 4.28
Using both PC(web) and mobile version. 

>if i wanna make the word 안녕, simplenote shows me ㅇㅏㄴㄴㅕㅇ. i cannot combine each other. 

I'm confirming if this just for tags or for note content too and if they notice it on a specific platform. 

It may also be 427-gh-Automattic/simplenote-ios-private

This user has confirmed this only happens with Tags, so moving this to the other issue.

**Comment by codebykat** [comment]
This issue is pretty useless since it is platform dependent and I believe we have issues for it in the relevant platform repos. Please check in simplenote-ios, simplenote-android and simplenote-electron repos and open new issues if needed.
