### ISSUE TITLE
Footnote Markdown Crashes iOS

### ISSUE THREAD

**Issue by mgalbritton** [Automattic/Simplenote-United#39]
When using footnotes via markdown, iOS crashes. 

### Expected
Expected: to be able to jump to a footnote in a note

### Observed
Observed: Simplenote crashes upon clicking on the footnote link

### Reproduced
1.) Add the sample text:
``` markdown
#Footnote test

This is a *Markdown*[^md] test note, showing the power of `.md` files[^which] to support footnotes.

[^md]: Markdown is a lightweight markup language that hasn't officially been updated in fourteen years.

[^which]: [Some Markdown versions](https://michelf.ca/projects/php-markdown/extra/#footnotes) support footnotes, while [others](https://github.github.com/gfm/) do not.
```

2.) Open up Simplenote in iOS.

3.) Swipe to preview the note and click on the footnote link

4.) Watch app crash

Screen recording:
![recording](https://testmegansite.blog/wp-content/uploads/2019/06/RPReplay_Final1560347719.mp4)

Make|Model|OS Version|App Version
-|-|-|-
iPhone|7|12.3|4.7.0

**Comment by bummytime** [comment]
@mgalbritton I am closing this because it was fixed in https://github.com/Automattic/simplenote-ios/pull/314. Our upcoming release will have the update! 🎉
