### ISSUE TITLE
Sorting: Notes sorted alphabetically can be ordered differently in different apps

### ISSUE THREAD

**Issue by rachelmcr** [Automattic/Simplenote-United#43]
### Expected

Using two Simplenote apps with same sort settings, I expect the notes to appear in the same order.

### Observed

While testing alphabetical sorting, I noticed that the iOS/Android and web apps treat newline characters differently:

If a note starts with a new line, iOS & Android sort it at the top of the list while the web ignores the newline character and sorts it alphabetically by the first letter/punctuation character.

### Reproduced

1. Create a note with a new line before any text.
2. Create a note with letters at the start of the note.
3. In the iOS or Android app, set it to sort alphabetically (A-Z).
4. In the web app, set it to sort alphabetically (ascending).
5. Compare the sort order.

Note that the note with the new line at the start of the note appears first in the iOS/Android apps, while it appears in alphabetical order ignoring the new line on the web.

Make|Model|OS Version|App Version
-|-|-|-
Apple|iPhoneXS | iOS 12.3.1 | Simplenote iOS 4.8.0 beta
Motorola|moto e5 Play | Android 8.1.0 | Simplenote Android 1.8 beta
Apple|macOS 10.14.5 | Chrome 75.0.3770.100 | app.simplenote.com web app

**Comment by bummytime** [comment]
@jleandroperez @theck13 @belcherj — any thoughts on this one?

**Comment by theck13** [comment]
We discussed and reproduced this on Android and iOS.  We'll create issues in each repository to make the mobile apps mimic the web alphabetical sorting.

**Comment by rachelmcr** [comment]
A related issue was opened on the iOS side here: https://github.com/Automattic/simplenote-ios/issues/340

**Comment by thehenrybyrd** [comment]
Another instance of this is with the character `_`, which gets sorted to the end of the list in Android, but the beginning of the list in Windows.
I initially thought this had to do with the Kanji the user is using, but with a bit of testing I was able to reproduce alphabetical sorting of `_` to the end of the list on Android. 
On app.simplenote.com, notes beginning with `_` appear at the start of the list in alphabetical sorting.

#2346082-zen

**Comment by codebykat** [comment]
The web now sorts the newline notes to the top of the list, so if iOS and Android haven't changed the behavior, I guess we've achieved consistency?

**Comment by belcherj** [comment]
Closing as iOS, macOS, and electron all function similarly.
