### ISSUE TITLE
Export Notes: Link in the top right-hand menu doesn't lead to the Export Notes page

### ISSUE THREAD

**Issue by ivan-ottinger** [Automattic/Simplenote-United#44]
Simplenote old web app - clicking on the **Export Notes** link in the top menu:

![Screen Shot 2019-07-22 at 09 36 44](https://user-images.githubusercontent.com/25105483/61615207-b92e3b80-ac65-11e9-8dc1-2107c18049e1.png)

will display the following message:

![Screen Shot on 2019-07-22 at 09:48:07](https://user-images.githubusercontent.com/25105483/61615274-e24ecc00-ac65-11e9-950d-cfa636d8e908.png)

### Expected

Clicking on the **OK** button should get us to this page:

![Screen Shot on 2019-07-22 at 09:49:30](https://user-images.githubusercontent.com/25105483/61615332-0dd1b680-ac66-11e9-8c24-f328786d2b27.png)

### Observed

instead, we are taken to the Simplenote new app only.

### Reproduced

Simplenote web app (old). Doesn't seem to be browser / system / OS related. Reproduced on:

Chrome Version 75.0.3770.100 (Official Build) (64-bit) |macOS 10.14.5|Simplenote web app (old)
Firefox 67.0.1 (64-bit) (64-bit) |macOS 10.14.5|Simplenote web app (old)

**Comment by codebykat** [comment]
Thanks for this report! We don't have any way to directly link to this dialog in the new webapp, which is why the dialog gives specific directions how to get there. I appreciate it's not the most convenient but it's not a priority for us to fix since we're not updating the old webapp any longer.
