### ISSUE TITLE
Markdown: Strikethrough Inconsistent

### ISSUE THREAD

**Issue by mgalbritton** [Automattic/Simplenote-United#47]
### Expected
Strikethrough markdown `~~strikethrough~~` looks fine on preview across electron, macOS, iOS but when the note is published, the strikethrough does not display and instead shows the markdown.

### Observed
The strikethrough does not display but the markdown is shown instead.

### Reproduced
1. Create a note with markdown enabled.
2. Add text such as `~~strikethrough~~`.
3. Check the preview and see it display as ~~strikethrough~~
4. Publish the note and check the published note..
5. See it display as `~~strikethrough~~`

Make|Model|OS Version|App Version
-|-|-|-
apple|mbp|10.14.6|web

**Comment by codebykat** [comment]
This should be fixed now!
