### ISSUE TITLE
Passwords Less Than 6 Characters Get Login Error

### ISSUE THREAD

**Issue by mgalbritton** [Automattic/Simplenote-United#48]
In the new web app, we've changed the password requirements to be a pass at least 6 characters long. If a user has a pass with less than 6 characters, they aren't able to login and get an error that says `Password must be at least 6 characters`. 

### Expected
If the pass is less than 6 characters, a nudge to update the password to fit within the new requirements. 

### Observed
An error message appears with no apparent way to fix the issue. 

### Reproduced
I wasn't able to reproduce this one, as my pass is already longer than 6 characters and I can't change it to be less than 6. 

This is only happening on the new web app, across various browsers. As a temporary fix, I've sent users the password reset link. 

See #2283496-zen  and #2283426-zen

**Comment by flow2k** [comment]
I'm a user in this category and I have this issue. Is changing my password mandatory now?

**Comment by mgalbritton** [comment]
> I'm a user in this category and I have this issue. Is changing my password mandatory now?

Hi there. You can reset your password here to one that is 6 characters or longer: 
https://app.simplenote.com/forgot/

If you have any trouble, send us an email to support@simplenoteapp.com. Thanks!

**Comment by codebykat** [comment]
This should be fixed incidentally by our recent upgrades to the password requirements (and the new nudge to change password). The login form still accepts 4-character passwords but then requires the password be changed.
