### ISSUE TITLE
Markdown: inconsistent tables support

### ISSUE THREAD

**Issue by iblazhko** [Automattic/Simplenote-United#5]
Markdown tables support is inconsistent across the platforms.

### Steps to reproduce:

1) Create a note with the following content:

```
Tables test
===

| Tables        | Are           | Cool  |
| ------------- |:-------------:| -----:|
| **col 3 is**  | right-aligned | $1600 |
| col 2 is      | *centered*    |   $12 |
| zebra stripes | ~~are neat~~  |    $1 |
```

2) Enable Markdown formatting for the note.

3) Preview the note in different apps on different platforms.

### Expected result:

The table above is rendered as a table in all supported platforms / apps.

### Actual result:

* Desktop app (Windows): rendered as a table
* Desktop app (Linux): rendered as a table
* Mobile app (Android): rendered as text
* Web app (`app.simplenote.com`): rendered as text

**Comment by codebykat** [comment]
Testing this, it is now rendered as a table on the web app, though the alignment seems to be ignored.
  
<img width="333" alt="Screen Shot 2020-06-18 at 11 05 20 PM" src="https://user-images.githubusercontent.com/52152/85101863-3c2e7d80-b1b8-11ea-8eba-fabe677903db.png">

**Comment by codebykat** [comment]
Update: Fix for alignment here, not shipped to web yet but will be soon https://github.com/Automattic/simplenote-electron/pull/2229

**Comment by codebykat** [comment]
Can we confirm if this is still an issue on Android @theck13? If it's fixed there I think we can close this

**Comment by theck13** [comment]
Android doesn't appear to have issues with tables.

<kbd><a href="https://user-images.githubusercontent.com/3827611/89036809-99126d00-d2fa-11ea-9371-2bbe673594c0.png"><img src="https://user-images.githubusercontent.com/3827611/89036809-99126d00-d2fa-11ea-9371-2bbe673594c0.png" width="300"></a></kbd>
