### ISSUE TITLE
Possibly thousands of "/n" being added to note after restart.

### ISSUE THREAD

**Issue by travisw** [Automattic/Simplenote-United#55]
A user reported in Zendesk, that after (maybe) restarting her phone, then checking a note she was editing before the restart, that:
a) The Android app could not load the note and was unresponsive.
b) Viewing the note on the web, showed an extra 80k worth of "/n" (I assume "\n") appended to the note.

It's not clear if it's an issue with the app or if her phone added the extra content.

Ticket: https://woothemes.zendesk.com/agent/tickets/2300448

### Expected
A note is in the same state as it was last left.

### Observed
a) The Android app could not load the note and was unresponsive.
b) Viewing the note on the web, showed an extra 80k worth of "/n" appended to the note.

### Reproduced
In the user's words:

1) I was cheerfully editing my "Tomatoes 2019" note in Simplenote for quite a while on my phone, then noticed my Pixel (Pixel 1) was ALMOST out of battery, attached it to power and was suprised to see it DIDN'T shut down.

2) (I of course have no memory of exactly what happened next, but the memory as stored in my brain is that I didn't do anything else. However, I MAY have restarted my Pixel because I've learned if I've almost lost power, odd things can happen and restarting often prevents further issues.)

3) I either re-opened or continued editing the "Tomatoes 2019" note only to find that the note was blank, the app seemed frozen, and finally the Pixel offered me the chance to Close, Wait, or Send Feedback (can't remember the exact text). After multiple tries of restarting the phone, restarting Simplenote, both on and off the web, I concluded I needed to try to access the note through my Mac or the web.

4) I was able to access the note through Simplenote on the Mac. It appeared that the note was now extremely long, with no additional readable text that I could see added. I copied the text I cared about into another file, then created a text file copied from my very long note, and confirmed that ~80K of newlines had been added.

5) I created a new note, copied in my text that I cared about (all of ~225 lines), "deleted" (moved to Trash) the problematic Very Large note (so Simplenote would stop trying to search it).

Make|Model|OS Version|App Version
-|-|-|-
Android|Pixel 1|9|1.8.2

**Comment by codebykat** [comment]
I can only assume this was a specific instance of https://github.com/Automattic/simplenote-android/issues/596 or possibly our old friend https://github.com/Automattic/simplenote-electron/issues/2030
