### ISSUE TITLE
Password / Secret / Spoiler field

### ISSUE THREAD

**Issue by shaneparsons** [Automattic/Simplenote-United#56]
### What
A way to hide passwords upon first glance, and only show the password when tapped... along the lines of spoiler tags.

### Why
Because of the free / syncing nature of Simplenote, it makes it a decent app to store passwords / keys in. I have done so, and often times I'll have to dig up a password / key for somebody, but because there isn't a way to hide the passwords the other person can often get a glance of all the other passwords along the way.

### How
There are likely multiple ways to go about doing this, but leveraging something like the markdown spoiler tag might be a good start:
e.g.
<details>
  <summary>Click to view password</summary>

  `password`

</details>

You could also do something along the lines of what turtl does, which is disguise passwords as `••••••` until clicked, revealing the password in place.

Either option could be linked to a new "Insert Password" format menu option, alongside "Insert Checklist".

**Comment by codebykat** [comment]
Thanks for the suggestion! I would say this is outside of Simplenote's purview and you would be better off using something like 1Password or LastPass.
