### ISSUE TITLE
Search for [ or ( will cause the web app to crash.

### ISSUE THREAD

**Issue by rezzap** [Automattic/Simplenote-United#73]
Please, be as descriptive as possible.  Issues lacking detail, or for any other reason than to report a bug, may be closed without action.

### Expected
I was expecting that if I searched for [ or ( in the web app I would get the results including these in my notes or at least return no result.

### Observed
The web page goes blank and the web app seems to crash instead. 

### Reproduced
> 1. Go to app.simplenote.com
> 2. Click on the search field and type in [, ( or )
> 3. See the screen go blank and the only option is to refresh to restore the app. 

![Screen Recording 2020-01-11 at 10 29 am](https://user-images.githubusercontent.com/10325627/72202956-5a4fbf00-345d-11ea-938a-bbc06189bb4b.gif)

Make|Model|OS Version|App Version
-|-|-|-
Apple|MacBook Pro 15" 2017|Catalina 10.15.2|Web app on Chrome 79.0.3945.88, Firefox 71.0 (64-bit

Reported in 2620175-zen

**Comment by codebykat** [comment]
Thanks, good catch! This is being tracked in https://github.com/Automattic/simplenote-electron (since it is only a problem on the web app) and will be fixed by https://github.com/Automattic/simplenote-electron/pull/1827.
