### ISSUE TITLE
Alphabetical sorting works a bit differently on different apps

### ISSUE THREAD

**Issue by msilbers** [Automattic/Simplenote-United#74]
On the Electron apps, `#` is not counted as a character to alphabetize, but it is on the other apps. So, on iOS I may see my notes sorted this way:

```
#1 
#2
#3
2019 taxes
```

On Electron it would be like this:

```
#1
#2
2019 taxes
#3
```

On Android apps: The titles starting with a capital letter are alphabetized, followed by the titles with lowercase letters in alphabetical order.

Like this:
Apple
Banana
Cat
Zebra
android
tabletop

reported here: https://github.com/Automattic/simplenote-android/issues/609

**Comment by thehenrybyrd** [comment]
Looks like this is related to: https://github.com/Automattic/Simplenote-United/issues/43

**Comment by codebykat** [comment]
No longer true in Electron:

<img width="321" alt="Screen Shot 2020-09-29 at 9 57 37 PM" src="https://user-images.githubusercontent.com/52152/94645012-994dcb00-029f-11eb-9979-b59572b58a38.png">

Since we're tracking the Android issue in simplenote-android, I'll close this.
