### ISSUE TITLE
Cannot generate public URL

### ISSUE THREAD

**Issue by Arty2** [Automattic/Simplenote-United#85]
Cannot generate public URL on certain notes. This seems to occur on specific notes, even when deleted and recreated with the same title and contents. Other notes do not exhibit this problem.

### Expected
Clicking on Make public link's switch, should return a public link.

### Observed
The switch stays enable for a moment, then returns to disabled without any error reported.

### Reproduced
- Clicking on Make public link's switch, should return a public link.
- The switch stays enable for a moment, then returns to disabled without any error reported.

Make|Model|OS Version|App Version
Web / Electron Windows app / Android app

**Comment by codebykat** [comment]
This didn't get triaged 😬 but for individual account/note issues it's always better to contact support directly so we can troubleshoot. https://simplenote.com/contact/

We do have better error reporting for this on our roadmap, but no estimate as to when it will happen.
