### ISSUE TITLE
app.simplenote.com/forgot in email doesn't take you to a password reset flow

### ISSUE THREAD

**Issue by allendav** [Automattic/Simplenote-United#94]
### Expected

Forgot I had a Simplenote account for allendav at automattic.com and tried to set it up again. Got a message saying that I already had an account (or something to that effect) which prompted me to try logging in using WordPress.com (federated) login. That worked.

![Screen Shot 2020-08-31 at 2 29 33 PM](https://user-images.githubusercontent.com/1595739/91771035-1a2d8000-eb97-11ea-8be0-e53e47051609.png)

### Observed

What I didn't expect was to receive this email. And clicking on the app.simplenote.com/forgot link in it didn't take me to anywhere to reset my password.

![Screen Shot 2020-08-31 at 2 24 22 PM](https://user-images.githubusercontent.com/1595739/91771081-30d3d700-eb97-11ea-868d-8844fa0be611.png)

### Reproduced

I repeated these steps, but I never received an email other than the first time.

### Where did you see the bug

- System Make: MacBook Pro
- System Model: 13-inch 2017 2.5 GHz Dual-Core Intel Core i7 16 GB 2133 MHz LPDDR3
- OS: macOS Catalina
- OS version: 10.15.6 (19G73)
- Browser (if applicable): 
- Browser version (if applicable): 
- Simplenote app version: 2.0

**Comment by codebykat** [comment]
Hi @allendav! I'm not sure this is a bug, I'm not familiar with this flow but it seems like the right thing to do when we get a login from WPCOM for an existing email address. What happened when you clicked on the https://app.simplenote.com/forgot/ link?
